name: Build and Release

on:
  push:
    tags:
      - 'v*'   # 仅在推送 v1.0.0 这样的 tag 时触发

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.9'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          output_name="G25WebDAV-${GOOS}-${GOARCH}"
          if [ "$GOOS" = "windows" ]; then
            output_name+=".exe"
          fi
          go build -ldflags="-s -w" -o $output_name main.go
          mkdir -p dist
          mv $output_name dist/

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: G25WebDAV-binaries
          path: dist/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: G25WebDAV-binaries
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
